### ISSUE TITLE
Compile Error after updating to version 2.11.0 from 2.10.0

### ISSUE THREAD

**Issue by udiedrichsen** [date-fns/date-fns#1686]
After updating from version 2.10.0 to 2.11.0 we got some errors.

Error: Cannot find module './add/index.js'

Failed to compile
./node_modules/date-fns/locale/be/_lib/formatRelative/index.js
Module not found: Can't resolve '../../../../_lib/isSameUTCWeek/index.js' in /node_modules/date-fns/locale/**be**/_lib/formatRelative'

and

./node_modules/date-fns/locale/**be**/_lib/formatRelative/index.js
[Frontend] Module not found: Can't resolve '../../../../_lib/isSameUTCWeek/index.js' in 'node_modules/date-fns/locale/be/_lib/formatRelative'

Both with locale **be**. We are not using this.

**Comment by dkozickis** [comment]
@udiedrichsen please check with [v2.11.1](https://github.com/date-fns/date-fns/releases/tag/v2.11.1)
