### ISSUE TITLE
parseISO doesnt return "Invalid date" when not a string

### ISSUE THREAD

**Issue by rejas** [date-fns/date-fns#3816]
After upgrading to v3.6 from the v2 branch, we noticed errors appearing in our logs:

```
parseISO.mjs:108 Uncaught TypeError: dateString.split is not a function
    at splitDateString (parseISO.mjs:108:1)
    at parseISO (parseISO.mjs:41:1)
    at getElapsedTime (utils.tsx:16:26) // our code that calls parseISO(timestampPossiblyUndefined)
```

Seems that when passing a non-string (like undefined in our case) to parseISO it doesnt check if its a string anymore and returns an "Invalid date" string no more

**Comment by adam-marshall** [comment]
The documentation https://date-fns.org/v3.6.0/docs/parseISO states

> If the argument isn't a string, the function cannot parse the string or the values are invalid, it returns Invalid Date.

We were on v2.8, the code used to include a check early in the method

```javascript
if (!(typeof argument === 'string' || Object.prototype.toString.call(argument) === '[object String]')) {
    return new Date(NaN);
}
```

before calling `splitDateString`

now it just calls `splitDateString` expecting a string.


I'd suggest either:
1. the check should be restored to `parseISO`
2. the documentation should be updated, to remove the _"If the argument isn't a string"_ bit.

**Comment by adam-marshall** [comment]
Looks like it was removed on this commit

https://github.com/date-fns/date-fns/pull/3141/commits/1e50bced1aa131b79ed2172a62c3727fe8e716e2#diff-ff2296eb27d158df704d066e8e91bbfc4191b0aa87003b24e232081c8b10440c

Description is "Remove implicit conversion of strings and booleans"

So it was added in 2.0 but removed in 3.0 

> BREAKING The arguments are not explicitly converted to the target types. Instead, they are passed as is, delegating this task to type checkers.

The point stands, if this is seen as desirable (my compiler didn't pick it up as we were calling it with `as string` anyway back in v2.8) then the documentation for the specific method should be updated.
