### PR TITLE
Add `@name` in constants jsdocs to fix type generation duplication

### LINKED ISSUE #3119: Duplicate variables in types (Cannot redeclare block-scoped variable 'daysInWeek')
Seems that in master the **typings.d.ts** has duplicate declared variables for **daysInWeek** (Line 1197)

`error TS2451: Cannot redeclare block-scoped variable 'daysInWeek'.

1195   const daysInWeek: number`

https://github.com/date-fns/date-fns/blob/master/typings.d.ts#L1197

duplicate-variable

Was introduced by the commit https://github.com/date-fns/date-fns/commit/6d8e424021f31edacc46b8b55a823fa3b54cc08c

### PR DESCRIPTION
**Pull request by fturmel**
Closes #3119

### CODE REVIEW

**Review by leshakoss — APPROVED** [review]
Oooff, thanks a lot!

**Comment by leshakoss** [comment]
Released as https://github.com/date-fns/date-fns/releases/tag/v2.29.1 Thank you so much @fturmel!

**Comment by fturmel** [comment]
@leshakoss You're welcome. Shoutout to @tom-spikeglobal for the early issue report before 2.29 was even released.

This is something the CI tests should've caught imo, I invite you to look at some old PRs I opened to improve the linter and type checks: #2948 #2949

Let me know in the PRs themselves if you're interested, and we can fix the current conflicts, etc. Some of the linter rules I added (fixing bad import paths, using `import type`, etc) are manually getting fixed and sneak back into the code base regularly.
