### ISSUE TITLE
Upgrade leads to 'Cannot augment module 'xxxx'  with value exports because it resolves to a non-module entity

### ISSUE THREAD

**Issue by MikeMitterer** [date-fns/date-fns#1683]
If I run `tsc --noEmit --incremental false` I get a long list of `Cannot augment...` error messages.
Everything was fine with 2.10.0 but fails now with 2.11.0

```
...
node_modules/date-fns/typings.d.ts:15311:9 - error TS2649: Cannot augment module 'ro' with value exports because it resolves to a non-module entity.

15311   const ro: Locale
              ~~

node_modules/date-fns/typings.d.ts:15314:9 - error TS2649: Cannot augment module 'ru' with value exports because it resolves to a non-module entity.

15314   const ru: Locale
              ~~

node_modules/date-fns/typings.d.ts:15317:9 - error TS2649: Cannot augment module 'sk' with value exports because it resolves to a non-module entity.
...
```

**Comment by dkozickis** [comment]
@MikeMitterer please check with [v2.11.1](https://github.com/date-fns/date-fns/releases/tag/v2.11.1)

**Comment by Moeriki** [comment]
I still have this issue with imports from `date-fns/fp`. Switching to non-fp fixes it.

**Comment by renilbabu03** [comment]
I have this issue in version 2.15.0

**Comment by MikeMitterer** [comment]
Yup - the same again. I had to downgrade to 

```
yarn add date-fns@2.11.1
```

**Comment by tonymartin-dev** [comment]
Same problem here

- System: Ubuntu 20.04
- Node version: 12.16.3
- Project: Angular v10

Downgrade to 2.11.1 didn't work

P.S.: When using same version of date-fns in an ionic+stencil project, it seems to work fine. Maybe some issue with Angular?

**Comment by davidmarquis** [comment]
I'm seeing the same issue when upgrading `date-fns` from `2.15.0` to `2.16.1`! 
Downgrading to `2.15.0` resolves this issue.
@dkozickis, FYI

**Comment by emondora** [comment]
same problem..2.16..

**Comment by MikeMitterer** [comment]
@dkozickis Can you please reopen this issue. As you can see the problem still exists. I tried it with 2.15.0 + 2.16.1 always the same problem. Only downgrading to 2.11.1. helps

I use date-fns in several modules. In some 2.16.1 works in others it fails.
Works with 2.16.1
```
import { differenceInSeconds, fromUnixTime } from 'date-fns'
import { formatISO9075 } from 'date-fns'
```

Works only with 2.11.1
```
import { formatISO, parseISO, toDate } from 'date-fns';
import { isSameDay, sub } from 'date-fns'
```

In both modules I remove unnecessary locales with
```
        // Weitere Infos: https://date-fns.org/docs/webpack
        new webpack.ContextReplacementPlugin(
            /date\-fns[\/\\]/,
            new RegExp(`[/\\\\\](${supportedLocales.join('|')})[/\\\\\]`)
        ),
```

**Comment by bennypowers** [comment]
I have this with date-fns 2.20.2, using typescript 4.2.3. In my project, the root of the repository has a package.json and contains frontend code, but the `/server` folder has its own package.json and contains cloud functions. Both packages use date-fns and have their own copies installed.

I'm getting around this by adding this to my CI, which is somewhat suboptimal

```bash
mv server/node_modules/date-fns/typings.d.ts bak
npm run build --prefix server
mv bak server/node_modules/date-fns/typings.d.ts
```

**Comment by shaynethiessen** [comment]
Why is this issue closed? I have the same problem.

**Comment by lperezp** [comment]
I momentarily added this inside tsconfig.json  `"skipLibCheck": true,`

- date-fns version: ^2.16.1
- Angular version: 11.2.1
- typescript version: ~4.1.5

**Comment by MikeMitterer** [comment]
Still struggling with this lib.

One thing that helps is:
```bash
yarn why date-fns
```

If yarn show multiple versions of date-fns you are f...
Make sure you have the same version of date-fns for all!!!!! you packages

**Comment by kazuooooo** [comment]
In my case, I include other package which depends date-fns other version.
The error was fixed by using the same version.
It looks typing information are conflicted between two versions.

**Comment by danielo515** [comment]
So, in my case 2.25.0 does not work, and introduces weird behaviours on libraries that depend on them.
Using 2.25.0 I get errors about not being able to resolve the module, and in fact on node_modules the folders are empty, just `d.ts` files there. Installing 2.24.0 fixes the problem, but I don't understand why.

If I use 2.25.0 this is what I get from `yarn why`:

```
➜  yarn why date-fns
yarn why v1.22.11
warning ../../../../../../package.json: No license field
[1/4] 🤔  Why do we have the module "date-fns"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "react@17.0.2" is incompatible with requested version "react@^16.8.3"
warning Resolution field "react@17.0.2" is incompatible with requested version "react@^16.8.3"
warning Resolution field "react@17.0.2" is incompatible with requested version "react@^16.8.3"
warning Resolution field "react-dom@17.0.2" is incompatible with requested version "react-dom@^16.8.3"
warning Resolution field "react@17.0.2" is incompatible with requested version "react@^16.8.0"
warning Resolution field "react-dom@17.0.2" is incompatible with requested version "react-dom@^16.8.0"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "date-fns@2.25.0"
info Has been hoisted to "date-fns"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "react-datepicker#date-fns"
info Disk size without dependencies: "11.73MB"
info Disk size with unique dependencies: "11.73MB"
info Disk size with transitive dependencies: "11.73MB"
info Number of shared dependencies: 0
=> Found "@types/react-datepicker#date-fns@2.21.3"
info This module exists because "@types#react-datepicker" depends on it.
info Disk size without dependencies: "28.57MB"
info Disk size with unique dependencies: "28.57MB"
info Disk size with transitive dependencies: "28.57MB"
info Number of shared dependencies: 0
✨  Done in 1.81s.
```

Please note the `=> Found "@types/react-datepicker#date-fns@2.21.3"` part.

However, if I change it to date-fns@2.24.0 this is what I get from `yarn why`:

```
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "date-fns@2.24.0"
info Has been hoisted to "date-fns"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "31.49MB"
info Disk size with unique dependencies: "31.49MB"
info Disk size with transitive dependencies: "31.49MB"
info Number of shared dependencies: 0
=> Found "@types/react-datepicker#date-fns@2.21.3"
info This module exists because "@types#react-datepicker" depends on it.
info Disk size without dependencies: "28.57MB"
info Disk size with unique dependencies: "28.57MB"
info Disk size with transitive dependencies: "28.57MB"
info Number of shared dependencies: 0
=> Found "react-datepicker#date-fns@2.25.0"
info This module exists because "react-datepicker" depends on it.
info Disk size without dependencies: "11.73MB"
info Disk size with unique dependencies: "11.73MB"
info Disk size with transitive dependencies: "11.73MB"
info Number of shared dependencies: 0
✨  Done in 2.16s.
```

Do you see it? It now resolves to `=> Found "react-datepicker#date-fns@2.25.0"`. What the hell is going on here?
At least 2.24.0 is working and I can stick to it, but I don't understand why this only fails for me.

**Comment by fturmel** [comment]
@danielo515 You might need to do a little song and dance to get to use only one version of date-fns v2 in your project. Have you tried deleting your `node_modules` and lock file, and run a fresh install?

You could also try to run `yarn cache clean` in case there is a corrupted copy of 2.25.0 in cache.

Adding the dependencies In an empty project doesn't seem to cause any conflicts for me.

<img width="430" alt="Screen Shot 2021-11-03 at 11 00 31 AM" src="https://user-images.githubusercontent.com/4009209/140085556-2a86a6b6-bcf7-47c7-af77-e072bac15b8a.png">

**Comment by danielo515** [comment]
Thanks for your reply @fturmel 

> Have you tried deleting your node_modules and lock file, and run a fresh install?

Deleting node_modules? Yes, dozens of times, but why would I delete the lock file? They are specifically to ensure you install the right versions. My team mates are using them and they have no problem with the libraries.

I'll try a yarn cache clean though, let's see how it goes

**Comment by danielo515** [comment]
Doing a `yarn cache clean` fixed the issue for me. Many thanks

**Comment by huangli112** [comment]
> I have this issue in version 2.15.0 . I am using this in Angular v9
> 
> `import { format } from 'date-fns';`
> 
> ![image](https://user-images.githubusercontent.com/18526147/87934719-3674d200-caad-11ea-9af0-906fe43d3c2a.png)

Ｉ　ｓｔｉｌｌ　ｈａｖｅ，　ｔｏｏ．ｓｏ　ｈｏｗ　ｃａｎ　ｙｏｕ　ｓｏｌｖｅ　ｉｔ？
