### ISSUE TITLE
Duplicate variables in types (Cannot redeclare block-scoped variable 'daysInWeek')

### ISSUE THREAD

**Issue by tom-spikeglobal** [date-fns/date-fns#3119]
Seems that in master the **typings.d.ts** has duplicate declared variables for **daysInWeek** (Line 1197)

`error TS2451: Cannot redeclare block-scoped variable 'daysInWeek'.

1195   const daysInWeek: number`

https://github.com/date-fns/date-fns/blob/master/typings.d.ts#L1197

![duplicate-variable](https://user-images.githubusercontent.com/87658684/180245027-d7a5d43d-ac4a-4b3a-a941-291e7dbaa6df.png)

Was introduced by the commit https://github.com/date-fns/date-fns/commit/6d8e424021f31edacc46b8b55a823fa3b54cc08c

**Comment by fturmel** [comment]
Good one.

@leshakoss @tan75 there is a missing `@name` jsdoc in the constants file. Pretty sure that's the root cause here, it's happened before.

https://github.com/date-fns/date-fns/blob/6d8e424021f31edacc46b8b55a823fa3b54cc08c/src/constants/index.ts#L11-L21

**Comment by steve3d** [comment]
confirmed in version 2.29.0, this also exists.

**Comment by harveyconnor** [comment]
yep getting this issue to

**Comment by s-a-m-u-e-l** [comment]
me toooo :(

**Comment by Kaspanoombro** [comment]
Me too.

**Comment by iMichaelOwolabi** [comment]
I am also getting this error now

**Comment by tinkermark-jeric** [comment]
Me too.

**Comment by jericepon** [comment]
I am getting this error too.

**Comment by DavidAmunga** [comment]
Damn. Same here !

**Comment by tazki** [comment]
got same error
![image](https://user-images.githubusercontent.com/42196376/180427824-7f4dc10d-36bc-4dd7-b6f9-05eb54cd0f67.png)

**Comment by gthau** [comment]
To workaround the issue, add "skipLibCheck": true  to your tsconfig.json, it will prevent tsc from type check your dependencies.
